packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nativescript/localize'

onlyBuiltDependencies:
  - '@nativescript/core'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - electron
  - utf-8-validate
